### ISSUE TITLE
Tools and Resources Subgroup: Public Dataset Committee and Tracking process- Chunlei, Liz

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#135]
From the Gov committee ...FYI Joel and @jguinney 

**Public Dataset Committee Dataset Tracking and posting**
_Tools and Resource Subgroup_

- [ ] Gov wants  a tracking report to with the list of external data sets requested, levels  (0-4) of datasets, status of review (where it is in the process...date requested, date committee reviewed, date DAC review, when implemented in the Enclave, which ones were rejected and why). Can work with @jmcmurry on a slide with that information that can be reported to Leadership. @fuentert and Liz 

- [ ] List of available data sets should be placed on the N3C website as Resource to Researchers.  Name of dataset, description, owner of dataset (organization). At first it can be just a list but once there are more than 20 a search feature is needed to search by type and keyword name.  @eichmann @amvolz 

- [ ] Set up dataset review Committee and report to Gov and N3C Leadership the status. @KenGersing

**Comment by andrewjneumann** [comment]
[is Jira 231](https://n3c-help.atlassian.net/servicedesk/customer/portal/2/N3CSUPPORT-231)
