### ISSUE TITLE
Tasks re: 7.22 N3C Enclave User Account walk-through 

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#51]
**TASKS**

1. **Onboarding  Form** @cgcook @eichmann 
- [x] Make modifications to registration form, direct user to N3C website to join groups [[details](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g8c98107609_5_12)]
- [x] Dropdown of Clinical specialties and roles
- [x] Slack email instead of slack ID

2.  **N3C Account transfer** @eichmann 
- [x] Associate all variations of organization with In-commons Organization (RORs) @eichmann 
- [x] Automate Connection from N3C to Foundry @eichmann @nqureshi Amin

3. **Foundry to UNA**
- [ ] API set up btwn Foundry to UNA @nqureshi Keats and Amin
- [ ] For approved DUA Account: auto create account @nqureshi Keats and Amin
- [ ] Generate Email to User @nqureshi and Amin

**4. DUR**
- [ ] Ability for researcher to click link to open new tab or go back to obtain link to send to collaborators…back @deacyma 
- [ ] Ability to View Code of Conduct @deacyma
- [ ] Improve wording to make it clear it is asking for Collaborators names @deacyma
- [ ] Need Collaborator Email Template @waldenan 
- [ ] Institution should auto populate in DUR

**5.  UNITE Landing page**
- [ ] Propose Improve usability (log in) @jmcmurry 
- [ ] Will discuss Citizen Scientist on Monday

**Comment by cgcook** [comment]
linked in [this issue](https://github.com/National-COVID-Cohort-Collaborative/operations/issues/57)
